const testWords = {
  stocks: "stonks",
  health: "helf",
  tech: "tehc",
  computer: "komputer",
  soccer: "sonker",
  moon: "mun",
  super: "sooper",
  business: "bizness",
  daniel: "doniel",
  jackson: "jonkson",
  jad: "jed",
  math: "meth",
  thick: "thicc",
  dick: "dicc",
  action: "aktion",
  word: "werd",
  huge: "yuge",
  drunk: "dronk",
  simpson: "sompson",
  poker: "ponker",
  think: "thonk",
  frog: "freg",
  fame: "feim"
};
